### PR TITLE
fix lua note stuff

### PR DESCRIPTION
**Pull request by SanicBTW**
ayo i saw this fork and well if you really want to use this for something i fixed custom notes lol

### CODE REVIEW

**Comment by Sylveondev** [comment]
Note fix :trollface:

**Comment by SanicBTW** [comment]
I doubt he is going to accept the pull request

**Comment by PaRappa1996** [comment]
doubt about what?

**Comment by SanicBTW** [comment]
well nvm you literally replaced kade engine input for old stinky 0.5.2h input

**Comment by Sylveondev** [comment]
💀 lol

**Comment by PaRappa1996** [comment]
:(

**Comment by Sylveondev** [comment]
I mean you could just like.. add it in yourself. It's your repo, ya know 🤷

**Comment by Sylveondev** [comment]
Most of your shaders don't work either. Probably wanna get that checked out.

**Comment by SanicBTW** [comment]
this ^^

**Comment by PaRappa1996** [comment]
i might check if i fixed the shaders

**Pull request closed without merging**
